### Pandas Export 

- to csv
- to excel
- to json
- to html
- to sql

In [1]:
import pandas as pd

### to_csv()

In [2]:
df = pd.read_csv('Data Sets/deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [4]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [6]:
temp_df.to_csv('Export DataSets/batsman_runs.csv', index=False)

### to_excel()

In [14]:
temp_df.to_excel('Export DataSets/batsman_runs.xlsx')

In [15]:
batter_vs_team = df.pivot_table(index='batsman', columns='bowling_team', values='batsman_runs', aggfunc='sum')

In [16]:
with pd.ExcelWriter('Export DataSets/batsman.xlsx') as writer:
    temp_df.to_excel(writer, sheet_name='batsman_runs')
    batter_vs_team.to_excel(writer, sheet_name='batsman_vs_team')

### to_html()

In [17]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [20]:
sixes = df.query('batsman_runs == 6').pivot_table(index='over', columns='ball', values='batsman_runs', aggfunc='count')
sixes

ball     1      2      3      4      5      6     7    8    9
over
1      7.0   12.0   27.0   31.0   24.0   20.0  12.0  1.0  NaN
2     26.0   30.0   35.0   43.0   45.0   42.0  10.0  5.0  NaN
3     63.0   46.0   57.0   52.0   48.0   58.0   8.0  2.0  1.0
4     49.0   61.0   51.0   81.0   54.0   53.0  11.0  1.0  NaN
5     54.0   56.0   82.0   64.0   62.0   60.0  10.0  2.0  NaN
6     61.0   82.0   44.0   65.0   56.0   66.0  11.0  1.0  NaN
7     27.0   45.0   34.0   44.0   51.0   28.0   3.0  3.0  NaN
8     44.0   47.0   55.0   49.0   53.0   39.0   7.0  NaN  NaN
9     70.0   56.0   56.0   58.0   52.0   35.0  11.0  NaN  1.0
10    43.0   38.0   60.0   43.0   52.0   54.0   9.0  1.0  NaN
11    59.0   70.0   62.0   54.0   61.0   56.0   8.0  NaN  NaN
12    70.0   58.0   72.0   63.0   65.0   52.0  11.0  1.0  NaN
13    67.0   87.0   58.0   80.0   75.0   65.0  10.0  2.0  NaN
14    83.0   85.0   79.0   74.0   65.0   71.0   7.0  3.0  NaN
15    68.0   93.0   83.0   74.0   64.0   86.0  11.0  1.0  NaN
16    77.0   96.0   95.0   91.0   91.0   78.0  15.0  2.0  NaN
17    84.0   88.0   86.0   87.0  103.0   78.0  20.0  3.0  NaN
18    91.0  111.0  112.0  115.0   94.0  101.0  17.0  1.0  1.0
19    82.0   90.0  114.0  103.0  111.0   98.0  31.0  6.0  3.0
20    99.0   95.0  106.0  113.0   88.0  102.0  24.0  5.0  NaN

In [21]:
sixes.to_html('Export DataSets/sixes.html')

### to_json()

In [22]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [26]:
players = df.groupby(['batting_team', 'batsman'])['batsman_runs'].sum().unstack()
players

batsman,A Ashish Reddy,A Chandila,A Chopra,A Choudhary,A Dananjaya,A Flintoff,A Hales,A Joseph,A Kumble,A Mishra,...,Y Nagar,Y Venugopal Rao,YA Abdulla,YK Pathan,YS Chahal,YV Takawale,Yashpal Singh,Younis Khan,Yuvraj Singh,Z Khan
batting_team,,,,,,,,,,,,,,,,,,,,,
Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Deccan Chargers,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,...,NaN,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Daredevils,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,...,285.0,468.0,NaN,NaN,NaN,NaN,NaN,NaN,248.0,10.0
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kings XI Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,964.0,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1893.0,NaN,NaN,47.0,NaN,NaN,NaN
Mumbai Indians,NaN,NaN,NaN,NaN,4.0,NaN,NaN,15.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,88.0,NaN,NaN,108.0,40.0
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,NaN
Rajasthan Royals,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1029.0,NaN,NaN,NaN,3.0,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,35.0,NaN,...,NaN,NaN,NaN,NaN,22.0,104.0,NaN,NaN,376.0,67.0
Sunrisers Hyderabad,245.0,NaN,NaN,NaN,NaN,NaN,152.0,NaN,NaN,93.0,...,NaN,71.0,NaN,319.0,NaN,NaN,NaN,NaN,488.0,NaN

In [28]:
clean_dict = players.apply(lambda col: col.dropna().to_dict()).to_dict()
clean_dict

{'A Ashish Reddy': {'Deccan Chargers': 35.0, 'Sunrisers Hyderabad': 245.0},
 'A Chandila': {'Rajasthan Royals': 4.0},
 'A Chopra': {'Kolkata Knight Riders': 53.0},
 'A Choudhary': {'Royal Challengers Bangalore': 25.0},
 'A Dananjaya': {'Mumbai Indians': 4.0},
 'A Flintoff': {'Chennai Super Kings': 62.0},
 'A Hales': {'Sunrisers Hyderabad': 152.0},
 'A Joseph': {'Mumbai Indians': 15.0},
 'A Kumble': {'Royal Challengers Bangalore': 35.0},
 'A Mishra': {'Deccan Chargers': 84.0,
  'Delhi Capitals': 27.0,
  'Delhi Daredevils': 164.0,
  'Sunrisers Hyderabad': 93.0},
 'A Mithun': {'Royal Challengers Bangalore': 34.0},
 'A Mukund': {'Chennai Super Kings': 0.0, 'Royal Challengers Bangalore': 19.0},
 'A Nehra': {'Chennai Super Kings': 1.0,
  'Delhi Daredevils': 25.0,
  'Mumbai Indians': 3.0,
  'Pune Warriors': 11.0,
  'Sunrisers Hyderabad': 1.0},
 'A Singh': {'Rajasthan Royals': 2.0},
 'A Symonds': {'Deccan Chargers': 839.0, 'Mumbai Indians': 135.0},
 'A Turner': {'Rajasthan Royals': 4.0},
 'A Uniyal': {'Rajasthan Royals': 4.0},
 'A Zampa': {'Rising Pune Supergiant': 5.0, 'Rising Pune Supergiants': 0.0},
 'AA Bilakhia': {'Deccan Chargers': 69.0},
 'AA Chavan': {'Rajasthan Royals': 12.0},
 'AA Jhunjhunwala': {'Deccan Chargers': 24.0,
  'Pune Warriors': 10.0,
  'Rajasthan Royals': 183.0},
 'AA Noffke': {'Royal Challengers Bangalore': 9.0},
 'AB Agarkar': {'Delhi Daredevils': 19.0, 'Kolkata Knight Riders': 160.0},
 'AB Barath': {'Kings XI Punjab': 42.0},
 'AB Dinda': {'Delhi Daredevils': 0.0,
  'Kolkata Knight Riders': 4.0,
  'Pune Warriors': 11.0,
  'Rising Pune Supergiant': 7.0,
  'Royal Challengers Bangalore': 4.0},
 'AB McDonald': {'Delhi Daredevils': 76.0,
  'Royal Challengers Bangalore': 47.0},
 'AB de Villiers': {'Delhi Daredevils': 671.0,
  'Royal Challengers Bangalore': 3757.0},
 'AC Blizzard': {'Mumbai Indians': 120.0},
 'AC Gilchrist': {'Deccan Chargers': 1220.0, 'Kings XI Punjab': 849.0},
 'AC Thomas': {'Pune Warriors': 20.0},
 'AC Voges': {'Rajasthan Royals': 181.0},
 'AD Mascarenhas': {'Kings XI Punjab': 19.0, 'Rajasthan Royals': 60.0},
 'AD Mathews': {'Delhi Daredevils': 176.0,
  'Kolkata Knight Riders': 249.0,
  'Pune Warriors': 299.0},
 'AD Nath': {'Gujarat Lions': 20.0,
  'Kings XI Punjab': 9.0,
  'Royal Challengers Bangalore': 62.0},
 'AD Russell': {'Delhi Daredevils': 58.0, 'Kolkata Knight Riders': 1387.0},
 'AF Milne': {'Royal Challengers Bangalore': 7.0},
 'AG Murtaza': {'Mumbai Indians': 2.0, 'Pune Warriors': 8.0},
 'AG Paunikar': {'Rajasthan Royals': 49.0},
 'AJ Finch': {'Delhi Daredevils': 102.0,
  'Gujarat Lions': 693.0,
  'Kings XI Punjab': 140.0,
  'Mumbai Indians': 23.0,
  'Pune Warriors': 456.0,
  'Rajasthan Royals': 21.0,
  'Sunrisers Hyderabad': 309.0},
 'AJ Tye': {'Gujarat Lions': 53.0, 'Kings XI Punjab': 41.0},
 'AL Menaria': {'Rajasthan Royals': 401.0},
 'AM Nayar': {'Kings XI Punjab': 106.0,
  'Mumbai Indians': 457.0,
  'Pune Warriors': 66.0,
  'Rajasthan Royals': 43.0},
 'AM Rahane': {'Mumbai Indians': 148.0,
  'Rajasthan Royals': 2840.0,
  'Rising Pune Supergiant': 382.0,
  'Rising Pune Supergiants': 480.0},
 'AN Ahmed': {'Mumbai Indians': 22.0, 'Royal Challengers Bangalore': 14.0},
 'AN Ghosh': {'Kolkata Knight Riders': 7.0},
 'AP Dole': {'Rajasthan Royals': 34.0},
 'AP Majumdar': {'Pune Warriors': 87.0},
 'AP Tare': {'Delhi Daredevils': 18.0,
  'Mumbai Indians': 313.0,
  'Sunrisers Hyderabad': 8.0},
 'AR Bawne': {'Delhi Daredevils': 12.0},
 'AR Patel': {'Delhi Capitals': 114.0, 'Kings XI Punjab': 692.0},
 'AS Rajpoot': {'Chennai Super Kings': 2.0,
  'Kings XI Punjab': 12.0,
  'Kolkata Knight Riders': 4.0},
 'AS Raut': {'Rajasthan Royals': 194.0},
 'AS Yadav': {'Deccan Chargers': 49.0, 'Mumbai Indians': 962.0},
 'AT Rayudu': {'Chennai Super Kings': 910.0, 'Mumbai Indians': 2416.0},
 'AUK Pathan': {'Royal Challengers Bangalore': 39.0},
 'Abdur Razzak': {'Royal Challengers Bangalore': 0.0},
 'Anirudh Singh': {'Deccan Chargers': 63.0},
 'Ankit Sharma': {'Deccan Chargers': 18.0,
  'Delhi Daredevils': 66.0,
  'Rajasthan Royals': 41.0,
  'Rising Pune Supergiant': 25.0,
  'Rising Pune Supergiants': 3.0,
  'Sunrisers Hyderabad': 11.0},
 'Ankit Soni': {'Gujarat Lions': 7.0},
 'Anureet Singh': {'Kings XI Punjab': 33.0, 'Rajasthan Royals': 4.0},
 'Avesh Khan': {'Delhi Capitals': 4.0},
 'Azhar Mahmood': {'Kings XI Punjab': 382.0, 'Kolkata Knight Riders': 6.0},
 'B Akhil': {'Kochi Tuskers Kerala': 13.0,
  'Royal Challengers Bangalore': 63.0},
 'B Chipli': {'Deccan Chargers': 244.0,
  'Delhi Daredevils': 16.0,
  'Royal Challengers Bangalore': 20.0},
 'B Kumar': {'Pune Warriors': 93.0, 'Sunrisers Hyderabad': 97.0},
 'B Laughlin': {'Chennai Super Kings': 4.0, 'Rajasthan Royals': 1.0},
 'B Lee': {'Kings XI Punjab': 56.0, 'Kolkata Knight Riders': 68.0},
 'B Stanlake': {'Sunrisers Hyderabad': 5.0},
 'B Sumanth': {'Deccan Chargers': 35.0},
 'BA Bhatt': {'Kings XI Punjab': 6.0},
 'BA Stokes': {'Rajasthan Royals': 331.0, 'Rising Pune Supergiant': 316.0},
 'BAW Mendis': {'Kolkata Knight Riders': 1.0, 'Pune Warriors': 2.0},
 'BB McCullum': {'Chennai Super Kings': 841.0,
  'Gujarat Lions': 674.0,
  'Kochi Tuskers Kerala': 357.0,
  'Kolkata Knight Riders': 883.0,
  'Royal Challengers Bangalore': 138.0},
 'BB Samantray': {'Deccan Chargers': 2.0, 'Sunrisers Hyderabad': 123.0},
 'BB Sran': {'Kings XI Punjab': 4.0,
  'Mumbai Indians': 3.0,
  'Sunrisers Hyderabad': 4.0},
 'BCJ Cutting': {'Mumbai Indians': 116.0,
  'Rajasthan Royals': 8.0,
  'Sunrisers Hyderabad': 116.0},
 'BE Hendricks': {'Kings XI Punjab': 1.0},
 'BJ Haddin': {'Kolkata Knight Riders': 18.0},
 'BJ Hodge': {'Kochi Tuskers Kerala': 285.0,
  'Kolkata Knight Riders': 476.0,
  'Rajasthan Royals': 639.0},
 'BJ Rohrer': {'Delhi Daredevils': 193.0},
 'BMAJ Mendis': {'Delhi Daredevils': 23.0},
 'BR Dunk': {'Mumbai Indians': 40.0},
 'Basil Thampi': {'Gujarat Lions': 28.0, 'Sunrisers Hyderabad': 4.0},
 'Bipul Sharma': {'Kings XI Punjab': 104.0, 'Sunrisers Hyderabad': 83.0},
 'C Ingram': {'Delhi Capitals': 187.0},
 'C Madan': {'Mumbai Indians': 15.0},
 'C Munro': {'Delhi Capitals': 87.0,
  'Delhi Daredevils': 63.0,
  'Kolkata Knight Riders': 30.0},
 'C Nanda': {'Mumbai Indians': 0.0},
 'C de Grandhomme': {'Kolkata Knight Riders': 126.0,
  'Royal Challengers Bangalore': 187.0},
 'CA Ingram': {'Delhi Daredevils': 21.0},
 'CA Lynn': {'Deccan Chargers': 6.0, 'Kolkata Knight Riders': 1302.0},
 'CA Pujara': {'Kings XI Punjab': 125.0,
  'Kolkata Knight Riders': 122.0,
  'Royal Challengers Bangalore': 143.0},
 'CH Gayle': {'Kings XI Punjab': 909.0,
  'Kolkata Knight Riders': 476.0,
  'Royal Challengers Bangalore': 3175.0},
 'CH Morris': {'Chennai Super Kings': 14.0,
  'Delhi Capitals': 34.0,
  'Delhi Daredevils': 396.0,
  'Rajasthan Royals': 76.0},
 'CJ Anderson': {'Delhi Daredevils': 142.0,
  'Mumbai Indians': 379.0,
  'Royal Challengers Bangalore': 17.0},
 'CJ Ferguson': {'Pune Warriors': 98.0},
 'CJ Jordan': {'Royal Challengers Bangalore': 3.0, 'Sunrisers Hyderabad': 0.0},
 'CJ McKay': {'Mumbai Indians': 8.0},
 'CK Kapugedera': {'Chennai Super Kings': 16.0},
 'CK Langeveldt': {'Kolkata Knight Riders': 0.0,
  'Royal Challengers Bangalore': 8.0},
 'CL White': {'Deccan Chargers': 583.0,
  'Royal Challengers Bangalore': 162.0,
  'Sunrisers Hyderabad': 226.0},
 'CM Gautam': {'Delhi Daredevils': 48.0, 'Mumbai Indians': 121.0},
 'CR Brathwaite': {'Delhi Daredevils': 95.0,
  'Kolkata Knight Riders': 12.0,
  'Sunrisers Hyderabad': 81.0},
 'CR Woakes': {'Kolkata Knight Riders': 46.0,
  'Royal Challengers Bangalore': 17.0},
 'CRD Fernando': {'Mumbai Indians': 4.0},
 'D Kalyankrishna': {'Deccan Chargers': 3.0},
 'D Salunkhe': {'Rajasthan Royals': 33.0},
 'D Shorey': {'Chennai Super Kings': 16.0},
 'D Short': {'Rajasthan Royals': 123.0},
 'D Wiese': {'Royal Challengers Bangalore': 127.0},
 'D du Preez': {'Royal Challengers Bangalore': 10.0},
 'DA Miller': {'Kings XI Punjab': 1875.0},
 'DA Warner': {'Delhi Daredevils': 1435.0, 'Sunrisers Hyderabad': 3306.0},
 'DAJ Bracewell': {'Delhi Daredevils': 12.0},
 'DB Das': {'Kolkata Knight Riders': 304.0},
 'DB Ravi Teja': {'Deccan Chargers': 361.0, 'Sunrisers Hyderabad': 14.0},
 'DE Bollinger': {'Chennai Super Kings': 21.0},
 'DH Yagnik': {'Rajasthan Royals': 170.0},
 'DJ Bravo': {'Chennai Super Kings': 942.0,
  'Gujarat Lions': 99.0,
  'Mumbai Indians': 457.0},
 'DJ Harris': {'Deccan Chargers': 111.0},
 'DJ Hooda': {'Rajasthan Royals': 151.0, 'Sunrisers Hyderabad': 384.0},
 'DJ Hussey': {'Chennai Super Kings': 116.0,
  'Kings XI Punjab': 695.0,
  'Kolkata Knight Riders': 511.0},
 'DJ Jacobs': {'Mumbai Indians': 92.0},
 'DJ Muthuswami': {'Delhi Daredevils': 1.0},
 'DJ Thornely': {'Mumbai Indians': 39.0},
 'DJG Sammy': {'Royal Challengers Bangalore': 13.0,
  'Sunrisers Hyderabad': 282.0},
 'DL Chahar': {'Chennai Super Kings': 59.0, 'Rising Pune Supergiant': 14.0},
 'DL Vettori': {'Delhi Daredevils': 67.0, 'Royal Challengers Bangalore': 54.0},
 'DM Bravo': {'Kolkata Knight Riders': 6.0},
 'DNT Zoysa': {'Deccan Chargers': 11.0},
 'DP Nannes': {'Delhi Daredevils': 4.0},
 'DP Vijaykumar': {'Deccan Chargers': 1.0},
 'DPMD Jayawardene': {'Delhi Daredevils': 666.0,
  'Kings XI Punjab': 843.0,
  'Kochi Tuskers Kerala': 299.0},
 'DR Martyn': {'Rajasthan Royals': 19.0},
 'DR Smith': {'Chennai Super Kings': 965.0,
  'Deccan Chargers': 237.0,
  'Gujarat Lions': 563.0,
  'Mumbai Indians': 620.0},
 'DS Kulkarni': {'Gujarat Lions': 28.0,
  'Mumbai Indians': 23.0,
  'Rajasthan Royals': 50.0},
 'DS Lehmann': {'Rajasthan Royals': 18.0},
 'DT Christian': {'Deccan Chargers': 335.0,
  'Delhi Daredevils': 28.0,
  'Rising Pune Supergiant': 79.0,
  'Royal Challengers Bangalore': 6.0},
 'DT Patil': {'Royal Challengers Bangalore': 13.0},
 'DW Steyn': {'Deccan Chargers': 55.0,
  'Gujarat Lions': 1.0,
  'Royal Challengers Bangalore': 15.0,
  'Sunrisers Hyderabad': 95.0},
 'E Lewis': {'Mumbai Indians': 464.0},
 'EJG Morgan': {'Kings XI Punjab': 65.0,
  'Kolkata Knight Riders': 444.0,
  'Royal Challengers Bangalore': 35.0,
  'Sunrisers Hyderabad': 310.0},
 'ER Dwivedi': {'Gujarat Lions': 24.0},
 'F Behardien': {'Kings XI Punjab': 14.0},
 'F du Plessis': {'Chennai Super Kings': 1660.0,
  'Rising Pune Supergiant': 8.0,
  'Rising Pune Supergiants': 206.0},
 'FH Edwards': {'Deccan Chargers': 4.0},
 'FY Fazal': {'Rajasthan Royals': 183.0},
 'G Gambhir': {'Delhi Daredevils': 1188.0, 'Kolkata Knight Riders': 3035.0},
 'GB Hogg': {'Kolkata Knight Riders': 7.0, 'Rajasthan Royals': 15.0},
 'GC Smith': {'Pune Warriors': 42.0, 'Rajasthan Royals': 697.0},
 'GD McGrath': {'Delhi Daredevils': 4.0},
 'GH Vihari': {'Sunrisers Hyderabad': 280.0},
 'GJ Bailey': {'Chennai Super Kings': 63.0,
  'Kings XI Punjab': 516.0,
  'Rising Pune Supergiants': 84.0},
 'GJ Maxwell': {'Delhi Daredevils': 180.0,
  'Kings XI Punjab': 1187.0,
  'Mumbai Indians': 36.0},
 'GR Napier': {'Mumbai Indians': 15.0},
 'Gurkeerat Singh': {'Kings XI Punjab': 342.0,
  'Royal Challengers Bangalore': 104.0},
 'H Brar': {'Kings XI Punjab': 22.0},
 'H Das': {'Deccan Chargers': 2.0},
 'H Gurney': {'Kolkata Knight Riders': 1.0},
 'H Klaasen': {'Rajasthan Royals': 58.0, 'Royal Challengers Bangalore': 10.0},
 'H Vihari': {'Delhi Capitals': 4.0},
 'H Viljoen': {'Kings XI Punjab': 6.0},
 'HH Gibbs': {'Deccan Chargers': 805.0, 'Mumbai Indians': 81.0},
 'HH Pandya': {'Mumbai Indians': 1118.0},
 'HM Amla': {'Kings XI Punjab': 577.0},
 'HV Patel': {'Delhi Capitals': 1.0,
  'Delhi Daredevils': 60.0,
  'Royal Challengers Bangalore': 47.0},
 'Harbhajan Singh': {'Chennai Super Kings': 35.0, 'Mumbai Indians': 799.0},
 'Harmeet Singh': {'Deccan Chargers': 0.0, 'Kings XI Punjab': 18.0},
 'Harpreet Singh': {'Pune Warriors': 20.0},
 'I Malhotra': {'Deccan Chargers': 7.0},
 'I Sharma': {'Deccan Chargers': 4.0,
  'Delhi Capitals': 10.0,
  'Kings XI Punjab': 8.0,
  'Kolkata Knight Riders': 33.0},
 'I Sodhi': {'Rajasthan Royals': 10.0},
 'IC Pandey': {'Pune Warriors': 0.0},
 'IK Pathan': {'Delhi Daredevils': 479.0,
  'Gujarat Lions': 2.0,
  'Kings XI Punjab': 603.0,
  'Rising Pune Supergiants': 11.0,
  'Sunrisers Hyderabad': 55.0},
 'IR Jaggi': {'Deccan Chargers': 43.0, 'Kolkata Knight Riders': 33.0},
 'Imran Tahir': {'Chennai Super Kings': 2.0,
  'Delhi Daredevils': 18.0,
  'Rising Pune Supergiant': 0.0},
 'Iqbal Abdulla': {'Kolkata Knight Riders': 26.0,
  'Royal Challengers Bangalore': 62.0},
 'Ishan Kishan': {'Gujarat Lions': 319.0, 'Mumbai Indians': 392.0},
 'J Archer': {'Rajasthan Royals': 85.0},
 'J Arunkumar': {'Royal Challengers Bangalore': 23.0},
 'J Bairstow': {'Sunrisers Hyderabad': 468.0},
 'J Botha': {'Delhi Daredevils': 43.0,
  'Kolkata Knight Riders': 31.0,
  'Rajasthan Royals': 335.0},
 'J Denly': {'Kolkata Knight Riders': 0.0},
 'J Searles': {'Kolkata Knight Riders': 8.0},
 'J Suchith': {'Delhi Capitals': 6.0, 'Mumbai Indians': 48.0},
 'J Syed Mohammad': {'Royal Challengers Bangalore': 29.0},
 'J Theron': {'Deccan Chargers': 7.0,
  'Kings XI Punjab': 2.0,
  'Rajasthan Royals': 1.0},
 'J Yadav': {'Delhi Daredevils': 6.0},
 'JA Morkel': {'Chennai Super Kings': 828.0,
  'Delhi Daredevils': 86.0,
  'Rising Pune Supergiants': 16.0,
  'Royal Challengers Bangalore': 45.0},
 'JC Buttler': {'Mumbai Indians': 528.0, 'Rajasthan Royals': 903.0},
 'JD Ryder': {'Pune Warriors': 548.0, 'Royal Challengers Bangalore': 56.0},
 'JD Unadkat': {'Delhi Daredevils': 1.0,
  'Rajasthan Royals': 50.0,
  'Rising Pune Supergiant': 2.0,
  'Royal Challengers Bangalore': 2.0},
 'JDP Oram': {'Chennai Super Kings': 106.0, 'Rajasthan Royals': 0.0},
 'JDS Neesham': {'Delhi Daredevils': 42.0},
 'JE Taylor': {'Pune Warriors': 3.0},
 'JEC Franklin': {'Mumbai Indians': 327.0},
 'JH Kallis': {'Kolkata Knight Riders': 1295.0,
  'Royal Challengers Bangalore': 1132.0},
 'JJ Bumrah': {'Mumbai Indians': 37.0},
 'JJ Roy': {'Delhi Daredevils': 127.0, 'Gujarat Lions': 59.0},
 'JJ van der Wath': {'Royal Challengers Bangalore': 18.0},
 'JM Kemp': {'Chennai Super Kings': 26.0},
 'JO Holder': {'Kolkata Knight Riders': 22.0, 'Sunrisers Hyderabad': 16.0},
 'JP Duminy': {'Deccan Chargers': 449.0,
  'Delhi Daredevils': 1015.0,
  'Mumbai Indians': 577.0},
 'JP Faulkner': {'Gujarat Lions': 131.0,
  'Kings XI Punjab': 14.0,
  'Rajasthan Royals': 382.0},
 'JR Hopes': {'Delhi Daredevils': 196.0, 'Kings XI Punjab': 221.0},
 'Jaskaran Singh': {'Deccan Chargers': 8.0},
 'Joginder Sharma': {'Chennai Super Kings': 36.0},
 'K Ahmed': {'Sunrisers Hyderabad': 0.0},
 'K Goel': {'Kings XI Punjab': 218.0},
 'K Gowtham': {'Rajasthan Royals': 148.0},
 'K Paul': {'Delhi Capitals': 22.0},
 'K Rabada': {'Delhi Capitals': 15.0, 'Delhi Daredevils': 55.0},
 'K Upadhyay': {'Pune Warriors': 12.0},
 'KA Pollard': {'Mumbai Indians': 2784.0},
 'KAJ Roach': {'Deccan Chargers': 10.0},
 'KB Arun Karthik': {'Chennai Super Kings': 3.0,
  'Royal Challengers Bangalore': 48.0},
 'KC Cariappa': {'Kings XI Punjab': 15.0, 'Kolkata Knight Riders': 9.0},
 'KC Sangakkara': {'Deccan Chargers': 558.0,
  'Kings XI Punjab': 1009.0,
  'Sunrisers Hyderabad': 120.0},
 'KD Karthik': {'Delhi Daredevils': 1036.0,
  'Gujarat Lions': 696.0,
  'Kings XI Punjab': 282.0,
  'Kolkata Knight Riders': 785.0,
  'Mumbai Indians': 748.0,
  'Royal Challengers Bangalore': 141.0},
 'KH Pandya': {'Mumbai Indians': 915.0},
 'KJ Abbott': {'Kings XI Punjab': 13.0},
 'KK Cooper': {'Rajasthan Royals': 116.0},
 'KK Nair': {'Delhi Daredevils': 638.0,
  'Kings XI Punjab': 312.0,
  'Rajasthan Royals': 511.0,
  'Royal Challengers Bangalore': 9.0},
 'KL Rahul': {'Kings XI Punjab': 1288.0,
  'Royal Challengers Bangalore': 417.0,
  'Sunrisers Hyderabad': 308.0},
 'KM Jadhav': {'Chennai Super Kings': 198.0,
  'Delhi Daredevils': 566.0,
  'Kochi Tuskers Kerala': 18.0,
  'Royal Challengers Bangalore': 309.0},
 'KMDN Kulasekara': {'Chennai Super Kings': 5.0},
 'KP Appanna': {'Royal Challengers Bangalore': 2.0},
 'KP Pietersen': {'Delhi Daredevils': 599.0,
  'Rising Pune Supergiants': 73.0,
  'Royal Challengers Bangalore': 329.0},
 'KS Williamson': {'Sunrisers Hyderabad': 1319.0},
 'KV Sharma': {'Mumbai Indians': 49.0,
  'Royal Challengers Bangalore': 1.0,
  'Sunrisers Hyderabad': 267.0},
 'KW Richardson': {'Pune Warriors': 34.0,
  'Rajasthan Royals': 1.0,
  'Royal Challengers Bangalore': 1.0},
 'Kamran Akmal': {'Rajasthan Royals': 128.0},
 'Kamran Khan': {'Rajasthan Royals': 3.0},
 'Karanveer Singh': {'Kings XI Punjab': 12.0},
 'Kuldeep Yadav': {'Kolkata Knight Riders': 46.0},
 'L Ablish': {'Kings XI Punjab': 0.0},
 'L Balaji': {'Chennai Super Kings': 22.0,
  'Kings XI Punjab': 1.0,
  'Kolkata Knight Riders': 13.0},
 'L Livingstone': {'Rajasthan Royals': 72.0},
 'L Plunkett': {'Delhi Daredevils': 1.0},
 'L Ronchi': {'Mumbai Indians': 34.0},
 'LA Carseldine': {'Rajasthan Royals': 81.0},
 'LA Pomersbach': {'Kings XI Punjab': 251.0,
  'Royal Challengers Bangalore': 51.0},
 'LH Ferguson': {'Rising Pune Supergiant': 1.0},
 'LJ Wright': {'Pune Warriors': 106.0},
 'LMP Simmons': {'Mumbai Indians': 1079.0},
 'LPC Silva': {'Deccan Chargers': 40.0},
 'LR Shukla': {'Delhi Daredevils': 31.0, 'Kolkata Knight Riders': 374.0},
 'LRPL Taylor': {'Delhi Daredevils': 256.0,
  'Pune Warriors': 63.0,
  'Rajasthan Royals': 181.0,
  'Royal Challengers Bangalore': 517.0},
 'M Ali': {'Royal Challengers Bangalore': 311.0},
 'M Ashwin': {'Kings XI Punjab': 3.0,
  'Rising Pune Supergiants': 0.0,
  'Royal Challengers Bangalore': 1.0},
 'M Kaif': {'Kings XI Punjab': 28.0,
  'Rajasthan Royals': 176.0,
  'Royal Challengers Bangalore': 55.0},
 'M Kartik': {'Kolkata Knight Riders': 73.0,
  'Pune Warriors': 38.0,
  'Royal Challengers Bangalore': 2.0},
 'M Klinger': {'Kochi Tuskers Kerala': 73.0},
 'M Lomror': {'Rajasthan Royals': 28.0},
 'M Manhas': {'Chennai Super Kings': 35.0,
  'Delhi Daredevils': 232.0,
  'Pune Warriors': 247.0},
 'M Markande': {'Mumbai Indians': 31.0},
 'M Morkel': {'Delhi Daredevils': 100.0,
  'Kolkata Knight Riders': 9.0,
  'Rajasthan Royals': 17.0},
 'M Muralitharan': {'Chennai Super Kings': 9.0,
  'Kochi Tuskers Kerala': 5.0,
  'Royal Challengers Bangalore': 6.0},
 'M Ntini': {'Chennai Super Kings': 11.0},
 'M Rawat': {'Pune Warriors': 5.0, 'Rajasthan Royals': 50.0},
 'M Santner': {'Chennai Super Kings': 35.0},
 'M Ur Rahman': {'Kings XI Punjab': 12.0},
 'M Vijay': {'Chennai Super Kings': 1679.0,
  'Delhi Daredevils': 207.0,
  'Kings XI Punjab': 704.0},
 'M Vohra': {'Kings XI Punjab': 957.0, 'Royal Challengers Bangalore': 59.0},
 'M Wood': {'Chennai Super Kings': 3.0},
 'M de Lange': {'Mumbai Indians': 1.0},
 'MA Agarwal': {'Delhi Daredevils': 355.0,
  'Kings XI Punjab': 462.0,
  'Rising Pune Supergiant': 26.0,
  'Royal Challengers Bangalore': 433.0},
 'MA Khote': {'Mumbai Indians': 24.0},
 'MA Starc': {'Royal Challengers Bangalore': 96.0},
 'MC Henriques': {'Delhi Daredevils': 11.0,
  'Kolkata Knight Riders': 38.0,
  'Royal Challengers Bangalore': 165.0,
  'Sunrisers Hyderabad': 755.0},
 'MC Juneja': {'Delhi Daredevils': 125.0},
 'MD Mishra': {'Deccan Chargers': 166.0, 'Pune Warriors': 71.0},
 'MDKJ Perera': {'Rajasthan Royals': 14.0},
 'MEK Hussey': {'Chennai Super Kings': 1768.0, 'Mumbai Indians': 209.0},
 'MF Maharoof': {'Delhi Daredevils': 177.0},
 'MG Johnson': {'Kings XI Punjab': 92.0,
  'Kolkata Knight Riders': 17.0,
  'Mumbai Indians': 59.0},
 'MJ Clarke': {'Pune Warriors': 98.0},
 'MJ Guptill': {'Kings XI Punjab': 132.0,
  'Mumbai Indians': 57.0,
  'Sunrisers Hyderabad': 82.0},
 'MJ Lumb': {'Deccan Chargers': 0.0, 'Rajasthan Royals': 278.0},
 'MJ McClenaghan': {'Mumbai Indians': 91.0},
 'MK Pandey': {'Kolkata Knight Riders': 1278.0,
  'Mumbai Indians': 3.0,
  'Pune Warriors': 525.0,
  'Royal Challengers Bangalore': 417.0,
  'Sunrisers Hyderabad': 649.0},
 'MK Tiwary': {'Delhi Daredevils': 322.0,
  'Kings XI Punjab': 49.0,
  'Kolkata Knight Riders': 1002.0,
  'Rising Pune Supergiant': 324.0},
 'ML Hayden': {'Chennai Super Kings': 1107.0},
 'MM Patel': {'Gujarat Lions': 0.0,
  'Mumbai Indians': 2.0,
  'Rajasthan Royals': 37.0},
 'MM Sharma': {'Chennai Super Kings': 29.0, 'Kings XI Punjab': 95.0},
 'MN Samuels': {'Delhi Daredevils': 29.0, 'Pune Warriors': 132.0},

In [30]:
import json
with open('Export DataSets/players.json', 'w') as f:
    json.dump(clean_dict, f, indent=4)